name: bmad-film-preproduction-pack
version: 1.0.0
short-title: Film Pre-Production Pack
description: >-
  An expansion pack for film pre-production, incorporating the creative writing department and adding key roles like Director, Producer, and Cinematographer. Includes workflows for features, shorts, TV pilots, and commercials.
author: Jules
slashPrefix: bmad-film
